### PR TITLE
Update constants in PyMQI to 9.2.5

### PR DESCRIPTION
**Pull request by Skyler-Altol**
The constant files in PyMQI have limited development of new functionality for too long. That ends with this pull request. Once merged, we can begin writing the CNO class, as well as any other functionality that came with the 9.0.x, 9.1.x and 9.2.x CD releases that people would like to see incorporated into the library.

There is also one update to a test which makes the test be skipped if CHCKCLNT is set to `OPTIONAL` as the expected result of that test should only occur if this attribute is set to `REQUIRED`.

### CODE REVIEW

**Comment by Skyler-Altol** [comment]
@dsuch can you please approve running the workflows that are currently blocked above. The tests ran with no issues on my local machine, but obviously it'd be good to see if the CI pipeline also sees all relevant tests pass.

Assuming those tests pass, can you also then please merge this PR.

**Comment by Skyler-Altol** [comment]
I've checked the tests, those that failed are all related to python 3.5. It appears the tests are failing for a couple of reasons. The windows one complains about C++ build tools, (which has nothing to do with this PR), and the ubuntu 3.5 one complains about an import error related to python 3.5 being end of life, resulting in pip dropping support for it. The error explicitly asks for the user to upgrade their python version. All tests that weren't cancelled against 3.6+ passed, which is an indication that the changes I've made are stable.

**Comment by SeyfSV** [comment]
Hi @Skyler-Altol , please, rebase you PR to the current master. I fixed tests.

**Comment by Skyler-Altol** [comment]
> Hi @Skyler-Altol , please, rebase you PR to the current master. I fixed tests.

Hey SeyfSV, happy to do so. Though given the lack of attention to the rest of the commit, I'm guessing the constant updates won't be merged even if I rebase my PR. It's a shame to be honest, I had planned to bring over the CNO stuff once this was merged.

**Comment by SeyfSV** [comment]
@Skyler-Altol , can I close PR?

**Comment by Skyler-Altol** [comment]
Oh I forgot you can merge stuff too, thanks a ton @SeyfSV! Yes this can be closed :) Thanks for the rebase, I had planned to get to that tomorrow night.

**Pull request closed without merging**
