### PR TITLE
GH #220 Fix MQ_FILE_PATH presence

### PR DESCRIPTION
**Pull request by SeyfSV**
@matjung, can you check this fix?

@JoshMcMQ, I think, MQ_FILE_PATH should have a priority over default paths, what do you think?

### CODE REVIEW

**Comment by JoshMcMQ** [comment]
I think you are right.   Will it throw an error if that ENV variable is not set?

**Comment by SeyfSV** [comment]
I check it with Linux - it works without error.
I hope @matjung will test it with Windows

**Comment by matjung** [comment]
In windows it throws an error message if the variable is not set.

**Comment by SeyfSV** [comment]
What error does occur?

**Comment by SeyfSV** [comment]
Hi @atulk0, 

I found branch [mq9-path-fix](https://github.com/atulk0/pymqi/commits/mq9-path-fix) in your fork :). You use MQ_FILE_PATH in setup.py, in this PR we use it too.
Can you check this PR on Windows?

**Comment by atulk0** [comment]
> Hi @atulk0,
> 
> I found branch [mq9-path-fix](https://github.com/atulk0/pymqi/commits/mq9-path-fix) in your fork :). You use MQ_FILE_PATH in setup.py, in this PR we use it too.
> Can you check this PR on Windows?

Sure @SeyfSV

**Comment by atulk0** [comment]
@matjung as @SeyfSV mentioned, if you could let us know what is the error you get on Windows? What kind of MQ client installation do you have on your Windows machine? Is it distributable or system install?

**Comment by SeyfSV** [comment]
Initially it was Windows 10, but I think it does not matter
MQ can be different:
* system install to default directory

Error is:
raise KeyError(key) from None
KeyError: 'MQ_FILE_PATH'

Before pymqi installation you should check that MQ_FILE_PATH does not defined in the session environment variables.

You can check #220 for more info. It is simple issue, but it should be checked before merging it to master.

**Pull request merged**
