### PR TITLE
support for zos

### PR DESCRIPTION
**Pull request by salapat11**
Hi @SeyfSV, 

Thanks for the raw PCF code.  This PR has changes to support PCF on z/OS platform.  Can you please review?  These changes are valid for non z/OS queue managers also and tested successfully.

1. Use MQCFH_VERSION_3 for CFH header
2. Add Type=MQCFT_COMMAND_XR to support z/OS
3. Add MQGMO_CONVERT to get_opts when reading PCF response

### CODE REVIEW

**Comment by SeyfSV** [comment]
Hi @salapat11 ,
Why we should to convert message. Can it be optional?
What should occurs if MQGET return MQRC_FORMAT_ERROR?

**Comment by salapat11** [comment]
Hi @SeyfSV , message conversion is required to support messages from z/OS platform as they have a different encoding.  MQRC_FORMAT_ERROR is a good point but I am not sure if it can happen for the PCF responses.

**Comment by salapat11** [comment]
MQGMO_CONVERT can certainly be optional (defaulted to False) as it only applies for z/OS

**Comment by JoshMcMQ** [comment]
The example originally provided by @jjjw420 had a zos=True, is that still present,  if so why is it not good enough? 

```
pcf_c = PCFCommand(qmgr, ccsid=37, encoding=785, convert=True, zos=True)
```

**Comment by SeyfSV** [comment]
@JoshMcMQ , I did not use / see @jjjw420 implementation :(. As result current version does not contain PCFCommand.

@salapat11 , can you add ccsid=None, encoding=None, convert=True, zos=True to PCFExecute class constructor?

I checked this version with cyrillic queue description - behaviour is strange for me, but this behaviour does not apply to pymqi.

**Comment by salapat11** [comment]
@SeyfSV , are the flags "convert" and "zos" not the same?  If convert=True, then it is assumed to use the MQGMO_CONVERT option which supports z/OS.  I do not see where ccsid and encoding are used in the current implementation.

**Comment by JoshMcMQ** [comment]
This is the implementation I was referencing that I (incorrectly) thought @SeyfSV had based this on: https://github.com/jjjw420/pymqi/blob/master/code/pymqi/mq_pcf.py

**Comment by JoshMcMQ** [comment]
Looks like it is raised to escaped commands, this is handled differently on zos.

**Comment by salapat11** [comment]
"convert" is added to PCFExecute constructor and defaults to False.  MQGMO_CONVERT option is used when "convert" is True.

**Comment by SeyfSV** [comment]
@salapat11 New version released!

**Comment by salapat11** [comment]
@SeyfSV , thank you so much 👍

**Comment by jjjw420** [comment]
Nice Job!  

I tested basic PCF commands on ZOS and a couple of other platforms and all seems well.  Constructing the PCF messages and sending them to the command queue is the way to go.  

BTW:  about the "zos" and "convert" options from my initial implementation.   The "zos" option was indeed because ZOS lacks support for sending escape messages via PCF(eg. MQSC commands).    The "convert" option was to convert the codepage.  

Loving it!

**Pull request merged**
