### PR TITLE
Add support for 'with' statement

### LINKED ISSUE #160: Support with statement for QueueManager and Queue objects
`QueueManager` and `Queue` may leak resources.

Consider `queue.put` or another operation throwing an exception, `queue.close` or `qmgr.disconnect` may not be called till garbage collection occurs:
```
    qmgr = pymqi.connect(queue_manager, channel, conn_info)

    queue = pymqi.Queue(qmgr, queue_name)
    queue.put(message)
    queue.close()

    qmgr.disconnect()
```

Adding support for [context managers](https://www.python.org/dev/peps/pep-0343/) (i.e. `with` statement) would avoid this issue: the connection would be open whenever the block is entered, and closed whenever exited (be it the normal or the exceptional case).

This would support code, like the below, where the queue is closed and the queue manager is disconnected upon leaving the block:
```
    with pymqi.connect(queue_manager, channel, conn_info) as qmgr,
          pymqi.Queue(qmgr, queue_name) as queue:
        queue.put(message)
```

### PR DESCRIPTION
**Pull request by molnargab-ms**
Resolves #160

### CODE REVIEW

**Comment by molnargab-ms** [comment]
My legal team wanted me to add this disclaimer to the change:
> This software is contributed subject to the terms of the Apache License v.2.0. You may obtain a copy of the license at http://www.apache.org/licenses/LICENSE-2.0
> This software is licensed by the copyright holders and contributors "as is" and any express or implied warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose and any warranty of non-infringement, are disclaimed. In no event shall the copyright owner or contributors be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of use of this software, even if advised of the possibility of such damage.  This software may be redistributed to others only by effectively using this or another equivalent disclaimer in addition to any other required license terms.

**Comment by dsuch** [comment]
Hi @molnargab-ms,

I see that some checks, or in fact all of them, are failing - can you have a look at this, please?

Generally, I am open to the idea but this needs to be backward compatible for sure.

As to the request from the legal team, I understand the intention but there are two missing points:

* You cannot be an anonymous copyright holder - if you would like to be explicitly listed in the source code as holder of parts of the copyright then we need your full name

* The license of PyMQI is [here](https://github.com/dsuch/pymqi/blob/master/LICENSE). In spirit it is very similar to what Apache License v.2.0 uses and we will not mix the two. Please consult it with your legal because using our existing license should not be a controversial point.

Thank you.

**Comment by SeyfSV** [comment]
The cause of failing checks is `set-env` command deprication: `The `set-env` command is disabled`
It can be fixed by this patch:
```
diff --git a/.github/workflows/install-tests.yml b/.github/workflows/install-tests.yml
index c82db52..7208e64 100644
--- a/.github/workflows/install-tests.yml
+++ b/.github/workflows/install-tests.yml
@@ -35,7 +35,7 @@ jobs:
 
       - name: Install MQ Client
         id: setup-mqclient
-        uses: SeyfSV/setup-mqclient@v0.1.3
+        uses: SeyfSV/setup-mqclient@v0.1.4
         with:
           mq-client-version: ${{ matrix.mq-client-version }}
 
diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
index 1c0a064..7749449 100644
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -53,7 +53,7 @@ jobs:
 
       - name: Install MQ Client
         id: setup-mqclient
-        uses: SeyfSV/setup-mqclient@v0.1.3
+        uses: SeyfSV/setup-mqclient@v0.1.4
         with:
           mq-client-version: ${{ matrix.mq-client-version }}
```

**Comment by molnargab-ms** [comment]
We're ok with using the Python 2 license for the contribution:

> © 2020 Morgan Stanley
> 
> This software is contributed subject to the terms of the python-2.0 license. You may obtain a copy of the license at https://spdx.org/licenses/python-2.0.html.
>
> This software is licensed by the copyright holders and contributors "as is" and any express or implied warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose and any warranty of non-infringement, are disclaimed. In no event shall the copyright owner or contributors be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this software, even if advised of the possibility of such damage. This software may be redistributed to others only by effectively using this or another equivalent disclaimer in addition to any other required license terms.

**Comment by molnargab-ms** [comment]
> Generally, I am open to the idea but this needs to be backward compatible for sure. 

As far as I'm concerned this should be backwards compatible: `with` statements look for `__enter__` and `__exit__` methods that I've added newly: https://www.python.org/dev/peps/pep-0343/#abstract.

> I see that some checks, or in fact all of them, are failing - can you have a look at this, please?
I'll try the patch.

**Comment by SeyfSV** [comment]
Hi @molnargab-ms,

You added `__init__.py` file to the `tests` directory and it broke other tests.
I removed it and got other errors:
```
self = <pymqi.Queue object at 0x7fbce0c60690>

    def __realOpen(self):
        """Really open the queue."""
        if self.__qDesc is None:
            raise PYIFError('The Queue Descriptor has not been set.')
>       rv = pymqe.MQOPEN(self.__qMgr.getHandle(), self.__qDesc.pack(), self.__openOpts)
E       TypeError: an integer is required (got type tuple)

.tox/docker/lib/python3.7/site-packages/pymqi/__init__.py:1865: TypeError
```
Can you test your version with pytest or tox? All required preparation described in README file in tests directory.

**Comment by molnargab-ms** [comment]
Thanks, I think now I've managed to sort my environment out eventually.

**Comment by SeyfSV** [comment]
Hi @molnargab-ms ,
I checked this branch with tests from master branch - it did no pass :( And I suppose that some programs will stop working after merging this branch to master.
Also, you did great work by changing all examples and tests, but I think, it is not needed because people should have a choice: to use context manager or not. And we need separate examples and tests for both way.

**Pull request closed without merging**
