### PR TITLE
MQ constants in one namespace

### PR DESCRIPTION
**Pull request by JochemGit**
As discussed in this [issue](https://github.com/dsuch/pymqi/issues/187) I created a file `mqconstants.py` to provide all MQ constants in namespace `pymqi.mqconstants`.
Additionally I added an import in `__init__.py`. It works for me. It should not affect anything else.

### CODE REVIEW

**Comment by AlexandreYang** [comment]
> I just wanted to rename that module to const or mqconst from mqconstants, otherwise, it looks good to me.

@dsuch @JochemGit Shall we just import all the constants in `__init__.py` directly, it seems there is no risk of collision. That will avoid some typing.

**Comment by dsuch** [comment]
I would rather keep them separate - this will amount to hundreds of names in the namespace, making code completion more cumbersome.

**Comment by JochemGit** [comment]
Do it as @dsuch likes it. I am fine with it.

**Comment by AlexandreYang** [comment]
@JochemGit Do you mind making the change `mqconstants` to `const` ?

**Comment by JochemGit** [comment]
@AlexandreYang I chose the name in analogy to the java class [MQConstants](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.javadoc.doc/WMQJMSClasses/com/ibm/mq/constants/MQConstants.html), which implements the interfaces CMQC, CMQCFC, CMQXC, CMQZC and some others.
Why don't you like it?

**Comment by dsuch** [comment]
Dear PyMQI champions, I ask, let it be const without discussing it further - there is no real difference between all these names, I just chose it in compliance with my own programming conventions. Thanks a lot.

**Comment by dsuch** [comment]
@AlexandreYang There is nothing that I can think of to prevent a new release, I will do it soon.

**Comment by AlexandreYang** [comment]
Thanks.

**Pull request merged**
