### PR TITLE
Update MQCD for MQ v9.1.3

### PR DESCRIPTION
**Pull request by SeyfSV**

### CODE REVIEW

**Comment by chughts** [comment]
My one concern with this change is that when the MQ server does have TLS switched on then developers will start to see the error message 

````
ERROR:__main__:MQI Error. Comp: 2, Reason 2393: FAILED: MQRC_SSL_INITIALIZATION_ERROR
````

For which the solution will be to specify a post SSL version in the CD constructor

eg.
````
cd = pymqi.CD(Version=pymqi.CMQXC.MQCD_VERSION_11)
````

set the cypher spec

````
cd.SSLCipherSpec = ... 
````

use a SCO object to point at the client keys

````
sco = pymqi.SCO()
sco.KeyRepository = ...
````

and make use of `qmgr.connect_with_options`. 

So we will need an example in the examples documentation.

**Comment by chughts** [comment]
I have just tested my subscribe tests and am seeing something strange. So have reverted to the subscribe sample from https://dsuch.github.io/pymqi/examples.html and am seeing the same problem. 

I still need to test with a basic pymqi install to verify if it is a problem with this pull request or inside the current release. 

When I run the below sample with Python 2.7.16 all is ok, but with Python 3.7.3 I get an abort trap 6 on the `sub.sub(sub_desc=sub_desc)` line.


```python

import logging

import pymqi

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

queue_manager = 'QM1'
channel = 'DEV.APP.SVRCONN'
host = '127.0.0.1'
port = '1414'
topic_string = 'dev/'
msg = '1.3961'
conn_info = '%s(%s)' % (host, port)
user = 'app'
password = 'asfbfavfads'

qmgr = pymqi.QueueManager(None)
qmgr.connect_tcp_client(queue_manager, pymqi.CD(), channel, conn_info, user, password)

sub_desc = pymqi.SD()
sub_desc['Options'] = pymqi.CMQC.MQSO_CREATE + pymqi.CMQC.MQSO_RESUME + \
    pymqi.CMQC.MQSO_DURABLE + pymqi.CMQC.MQSO_MANAGED
sub_desc.set_vs('SubName', 'MySub')
sub_desc.set_vs('ObjectString', topic_string)

logging.info('Check line 27')
sub = pymqi.Subscription(qmgr)
logging.info('Check line 29')
sub.sub(sub_desc=sub_desc)
logging.info('Check line 30')

get_opts = pymqi.GMO(
    Options=pymqi.CMQC.MQGMO_NO_SYNCPOINT + pymqi.CMQC.MQGMO_FAIL_IF_QUIESCING + pymqi.CMQC.MQGMO_WAIT)
get_opts['WaitInterval'] = 15000

data = sub.get(None, pymqi.md(), get_opts)
logging.info('Here is the received data: [%s]' % data)

sub.close(sub_close_options=pymqi.CMQC.MQCO_KEEP_SUB, close_sub_queue=True)
qmgr.disconnect()


```

**Comment by SeyfSV** [comment]
Hi @chughts 
I tried your code and it successfully passes `sub.sub(sub_desc=sub_desc)` line.
Environment: Ubuntu, Python 3.7.3, MQ Server 9.1 and 8.0

**Comment by SeyfSV** [comment]
Also I ran `tests/test_pubsub.py` and it pass too.

**Comment by chughts** [comment]
I am running on a Mac 10.15 (Catalina). I have upgraded to Python 3.7.4 and rebuilt the environment, and the test and my code not run successfully.

**Comment by SeyfSV** [comment]
As I understand `abort trap 6` is some sort off access violation. And I think this patch is not cause of it.
Can you check test on pymqi v1.9.2 ?

**Comment by chughts** [comment]
@SeyfSV I just reread my last post, and there was a typo. I have corrected, and I wanted to say that with Python 3.7.4 it **did** run successfully.

**Comment by dsuch** [comment]
Hello everyone,

in the context of #139 - is it safe to merge this PR? Is it all ready?

Thanks.

**Comment by chughts** [comment]
I have been using this branch for a few weeks now without any problems. My code has needed to be amended to use  

```Python
        cd = pymqi.CD(Version=pymqi.CMQXC.MQCD_VERSION_11)
```

and for get by matching on correlation id 

```Python
    gmo.Version = pymqi.CMQC.MQGMO_VERSION_2
```

Having to set the gmo.Version so that a get by matching correlation id may cause some problems to  others who don't know that Version needs to be set.

**Comment by dsuch** [comment]
Thanks, I have just merged it in and will release a new PyMQI version soon.

**Comment by dsuch** [comment]
Version 1.9.3 is released, thanks again:

https://github.com/dsuch/pymqi/blob/master/changelog.md

**Pull request merged**
